style: fixed theming for buttons.
helsingborg-stad/app-mitt-helsingborg pull request #276
Opened 2020-10-29 18:55 UTC by zilaei

Tried to not change to much other then using our defined theme for coloring.
Removed custom colored buttons from stories, uncertain if these should be allowed.

2020-10-30 12:40 UTC, dannil76 requested changes
Minor

2020-10-30 12:40 UTC, dannil76 commented on source/components/atoms/Button/Button.stories.js
> +  // ))
Please remove unused code. Tip, save it in a gist. :)

2020-11-02 09:13 UTC, TeddyAndersson commented
Made some changes in addition to your changes @zilaei, hope you don't mind. The button should now be more in line with the figma design :)

2020-11-02 09:15 UTC, TeddyAndersson commented
However we have some additions that we need to make, and i think this is a good case for defining a button object in the theme object. But i do not think these changes is suited for this PR but rather another task. Since it's new styling to the button in general :)

2020-11-02 09:16 UTC, TeddyAndersson approved these changes
Looks good to me, good if someone can look over the last changes that i made :)

2020-11-02 09:19 UTC, dannil76 approved these changes

2020-11-02 09:21 UTC, merged

2020-11-02 09:23 UTC, zilaei commented
@TeddyAndersson: Changes welcomed and accepted! 👍