refactor: changed name on component FooterAction to StepFooter
helsingborg-stad/app-mitt-helsingborg pull request #303
Opened 2020-11-09 15:40 UTC by TeddyAndersson

## Explain the changes you’ve made

I've added support for theming the background color in a form steps footer, so that it always defaults to a shade of grey. 
In addition to this i've also renamed the component to StepFooter from FooterAction.

For more background, see [clickup task](https://app.clickup.com/t/fmrkhq)

## Explain why these changes are made

A good example:
These changes are a move towards using theming in the application that is set in a higher context than the individually component.

The renaming of the component was done due to that the component is only used together with a step in a form. Thereby the name StepFooter feels more natural than FooterAction.

For more background, see [clickup task](https://app.clickup.com/t/fmrkhq)

## Explain your solution

A Good example:
The solution for adding the theme is to use the ThemeContext provided through Styled-components and retreive the color data from that context.

## How to test the changes?

Concrete example:
1. Checkout this branch
2. Swap the application to run storybook
3. Fire upp the simulator by running the command`yarn ios`
4. Go to the story Footer.

## Was this feature tested in the following environments?
- [x] Storybook on a iOS device/simulator.
- [x] Building the Application on a iOS device/simulator.
- [] Building the Application on a Android device/simulator.

## Anyhting else? (optional)

The Footer should according to design be able to change color based on where in a Form you are, this functionality is not adressed here. Would need to have another round with the design team to check how important this aspect is right now.

2020-11-09 15:53 UTC, jwinding requested changes
I approve of the name change, StepFooter is much better. But something is not working as intended, the action buttons end up in wrong place and one of them disappears completely, see the screen shot below
![Screenshot 2020-11-09 at 16 49 48](https://user-images.githubusercontent.com/7421890/98563761-d9936680-22ab-11eb-9ec8-76065d4e84d4.png)
This has to be because you moved the 'position: absolute', but I don't fully understand it.

2020-11-10 13:42 UTC, TeddyAndersson commented
> I approve of the name change, StepFooter is much better. But something is not working as intended, the action buttons end up in wrong place and one of them disappears completely, see the screen shot below
> ![Screenshot 2020-11-09 at 16 49 48](https://user-images.githubusercontent.com/7421890/98563761-d9936680-22ab-11eb-9ec8-76065d4e84d4.png)
> This has to be because you moved the 'position: absolute', but I don't fully understand it.

Hmm yeah this is really strange, did not experience this behavior in my simulator. But might be to the move of the absolute positinging, even though it feels strange. Will look into this (y)

2020-11-10 13:43 UTC, TeddyAndersson commented
> I approve of the name change, StepFooter is much better. But something is not working as intended, the action buttons end up in wrong place and one of them disappears completely, see the screen shot below
> ![Screenshot 2020-11-09 at 16 49 48](https://user-images.githubusercontent.com/7421890/98563761-d9936680-22ab-11eb-9ec8-76065d4e84d4.png)
> This has to be because you moved the 'position: absolute', but I don't fully understand it.

Is this weird behavior in the app or in a storybook story?

2020-11-10 14:07 UTC, jwinding commented
> Is this weird behavior in the app or in a storybook story?

For me it was both. The screenshot is from the löpande form in the app.

2020-11-10 15:49 UTC, jwinding approved these changes
Now the buttons are where they should be, so it's approved!

2020-11-10 21:44 UTC, dannil76 approved these changes

2020-11-11 08:34 UTC, merged