Style/navigation button group
helsingborg-stad/app-mitt-helsingborg pull request #314
Opened 2020-11-12 13:05 UTC by TeddyAndersson

## Explain the changes you’ve made

Updated the Navigation Button Component to match design from Figma.

## Explain why these changes are made

The design was not considered when doing the first implementation of this component. Therefore a update to the design was nessecary.

## Explain your solution

The solution was to change the way that the Button component is rendered in the Navigation Button Component. So that the correct props is passed and so that children are passed in the correct way. 

Passing the children in the right order id important since we want the first child to be and icon and thereby display on the left side in the button content.

## How to test the changes?

1. Checkout this branch
2. Swap the application to run storybook
3. Fire upp the simulator by running the command`yarn ios`
4. Go to the NavigationButton Story.
5. Swap the application back to building the actual app.
6. Start a form with a navigation button group component.

## Was this feature tested in the following environments?
- [x] Storybook on a iOS device/simulator.
- [x] Building the Application on a iOS device/simulator.
- [ ] Building the Application on a Android device/simulator.

## Anyhting else? (optional)

There are a few additional comments added in the component that concerns the responsibility of navigation in a form, i think this could be simplified. 

My suggestion is to add a ButtonGroup component that can render one or more Buttons in vertical or horizontal manner. This component can be used to create a component that is smart and handels form navigation logics.

2020-11-12 13:27 UTC, dannil76 approved these changes

2020-11-12 13:42 UTC, jwinding requested changes
Looks good, but I get a few lint issues that can be fixed, and there's a console.log that can be removed. Also, if you added a story you forgot to commit it, because there's no NavigationButton story. 

In the form, no icons show up, but that's because the form name is not set. We probably want the default to be no icon though, so this is probably fine.

2020-11-12 13:42 UTC, jwinding commented on source/components/molecules/NavigationButtonField/NavigationButtonField.tsx
> +  console.log(iconName)
Remove console log.

2020-11-16 12:46 UTC, jwinding approved these changes

2020-11-16 12:46 UTC, merged