User agreement
helsingborg-stad/app-mitt-helsingborg pull request #369
Opened 2020-12-09 14:05 UTC by zilaei

## Explain the changes you’ve made

Added modal with user agreement in login screen.

## Explain why these changes are made

Juridical requirements.

## Explain your solution

Text in modal that is displayed when user presses the user agreement info.
The user agreement text is markdown formatted and can be found in assets.

## How to test the changes?

Logout and navigate to login screen and press on footer text "användaravtal".
![Screenshot 2020-12-09 at 15 01 17](https://user-images.githubusercontent.com/186287/101639581-c3560300-3a2f-11eb-8713-8711bf24a52b.png)

## Was this feature tested in the following environments?
- [ ] Storybook on a iOS device/simulator.
- [x] Building the Application on a iOS device/simulator.
- [ ] Building the Application on a Android device/simulator.

2020-12-09 15:40 UTC, jwinding requested changes
Looks good and works, just two minor things. See the comment for a minor thing about naming.

Otherwise from a usability perspective: the user agreement is long, so it would probably be good with a close button at the bottom, so that I don't have to scroll to the top to close the modal.

2020-12-09 15:40 UTC, jwinding commented on source/screens/LoginScreen.js
> +  const [userAgreementModal, setUserAgreementModalVisible] = useState(false);
Feels more consistent with loginModalVisible and userAgreementModalVisible maybe? But the names are getting a bit too long.

2020-12-09 16:21 UTC, dannil76 approved these changes
Hard coded stuff.... 🥇

2020-12-11 06:19 UTC, dannil76 approved these changes

2020-12-11 07:51 UTC, jwinding approved these changes

2020-12-11 08:24 UTC, merged