Validation of checkbox question
helsingborg-stad/app-mitt-helsingborg pull request #372
Opened 2020-12-11 06:19 UTC by zilaei

## Explain the changes you’ve made

Enabled validation for checkbox questions.
Added handling of equals validation, with single rule argument.

## Explain why these changes are made

These changes prevents the user from preceding without agreement.
See https://app.clickup.com/t/b4zax1 for more information.

## How to test the changes?

Run storybook -> Summary List -> Validation
Try out validation with the different input types and press Submit button.

## Was this feature tested in the following environments?
- [x] Storybook on a iOS device/simulator.
- [ ] Building the Application on a iOS device/simulator.
- [ ] Building the Application on a Android device/simulator.

## Anything else? (optional)

Validation error message not final. This task is left to design.

2020-12-11 08:52 UTC, jwinding requested changes
The validation seems to work as intended, so the main part is good.

But the way you add the error message under the checkbox is changing the layout of the checkbox in the form; basically the text next to the checkbox gets right-adjusted instead of going next to the checkbox (switch between this branch and develop to see). Maybe the error text should go in the CheckboxField component rather than Checkbox? Or perhaps some CSS on the Container in Checkbox might be enough...

2020-12-11 08:54 UTC, dannil76 approved these changes

2020-12-11 09:17 UTC, zilaei commented
> The validation seems to work as intended, so the main part is good.
> 
> But the way you add the error message under the checkbox is changing the layout of the checkbox in the form; basically the text next to the checkbox gets right-adjusted instead of going next to the checkbox (switch between this branch and develop to see). Maybe the error text should go in the CheckboxField component rather than Checkbox? Or perhaps some CSS on the Container in Checkbox might be enough...

Thanks for the feedback. Will have to discuss the layout before I can precede as I'm not seeing the same behavior.

2020-12-14 08:52 UTC, dannil76 reviewed
![Skärmavbild 2020-12-14 kl  09 52 01](https://user-images.githubusercontent.com/768077/102060142-19d98d80-3df2-11eb-8e9f-fb2f0e0558c1.png)

2020-12-15 13:00 UTC, jwinding approved these changes
Layout is correct and the error message looks good as well. And typescript, wonderful to see!

2020-12-15 13:02 UTC, jwinding commented
Had to rebase on top of updated dev in order to test, so I force-pushed this into the branch; there was just one trivial conflict in the ValidationHelper file.

2020-12-15 13:38 UTC, merged