feat(EditableList): display validation error message
helsingborg-stad/app-mitt-helsingborg pull request #420
Opened 2021-01-18 16:07 UTC by zilaei

## Explain the changes you’ve made

Display validation error message for component EditableList.

## How to test the changes?

A EditableList with validation can be found in form "Test form" on AWS dev. Try setting phone nr to something like "0738121212d". 

## Was this feature tested in the following environments?
- [ ] Storybook on a iOS device/simulator.
- [x] Building the Application on a iOS device/simulator.
- [ ] Building the Application on a Android device/simulator.

2021-01-19 08:41 UTC, jwinding approved these changes
Works!

2021-01-19 16:13 UTC, TeddyAndersson reviewed
Code works. But left som improvement suggestions for code readability.

2021-01-19 16:13 UTC, TeddyAndersson commented on source/components/molecules/EditableList/EditableList.js
> +          </>
Could be returned as an array of components instead of using react fragments ie <> </>

2021-01-19 16:13 UTC, TeddyAndersson commented on source/components/molecules/EditableList/EditableList.js
> +              <></>
Could be refactored for readability to
```
 const isInputValid = error && error[input.key]?.isValid === false
 ....
 {isInputValid && <StyledErrorText>{error[input.key].validationMessage}</StyledErrorText> }
```

2021-01-19 16:13 UTC, TeddyAndersson commented on source/components/molecules/EditableList/EditableList.js
> +              }}
Personal preference but rather se this function implemented as an handler function. ie
```
handlePressListItem() {
....
}

<EditableListItem .... onPress={handlePressItem} />
...
```

2021-01-20 09:49 UTC, TeddyAndersson requested changes
Found one potential breaking change and one improvment.

2021-01-20 09:49 UTC, TeddyAndersson commented on source/components/molecules/EditableList/EditableList.js
> +            onPress={(index) => handleListItemPress(index)}
Correct me if i'm wrong but the index defined here is the onPress event, should it not be defined as:
```
onPress={() => handleListItemPress(index)}

// the current code is rather a definition of:
onPress={(event) => handleListItemPress(event)}
```

2021-01-20 09:49 UTC, TeddyAndersson commented on source/components/molecules/EditableList/EditableList.js
> +          isInputValid(input) ? (
no need for ternary expression, the following should be enough:
```
isInputValid(input) && <StyledErrorText>{error[input.key].validationMessage}</StyledErrorText>
```

2021-01-20 12:24 UTC, TeddyAndersson approved these changes
Looks good, feel free to rebase 👍

2021-01-20 12:55 UTC, merged