Feat/close dialog
helsingborg-stad/app-mitt-helsingborg pull request #453
Opened 2021-02-16 16:15 UTC by nRamstedt

## Explain the changes you’ve made

- Refactor: CloseDialog (replace hard-coded content with props)
- Refactor: Dialog implementation within Step
- Add: FormDialog component
- Add: state, actions & implementation for 'snapshotting' answers
- Eslint: Disable prop-types linting within .tsx files
 
## Explain why these changes are made

- To allow users to discard changes done within a subform by pressing the X in the rop right corner.
- To make sure users cannot pass validation by pressing X

## Explain your solution

What to say, it's really great? uh no, it's the greatest!

## How to test the changes?

1. Start a form containing atleast 1 SummaryList component
2. Add an item with values to a SummaryList & hit save
3. Make sure item is visible & has correct values in the list after hitting save
4. Edit the same item again, this time hit X button in top right corner without making any changes
5. **Expected behaviour: should return to main step without a prompt (since we made no changes)**
6. Repeat step 4 but this time make some changes & hit X button
7. **Expected behaviour: Should display dialog asking the using wheter to discard or continue editing - choose to continue editing**
8. **Expected behaviour: Shoud close dialog and stay at the same substep - hit X button (one last time) & discard changes**
9. **Expected behaviour: Should return to main step and changes made within sub step should not be visible**

## Was this feature tested in the following environments?
- [] Storybook on a iOS device/simulator.
- [X] Building the Application on a iOS device/simulator.
- [] Building the Application on a Android device/simulator.

## Known limitations:

- Snapshot implementation does not account for forms with empty answers object (i believe we can live with this right now)
- Snapshot implementation does not account for save/restore JS-specific defintions (like date) within state.answers because of deep cloning through JSON
- Snapshot callbacks are forwarded through formNavigation
- Starting a form within a sub step may give a prompt even though you have not made any changes (which should never happen as the user shouldn't be able to start from a sub step).
- Exiting the application while editing a sub step may not restore answers correctly

2021-02-16 21:48 UTC, dannil76 requested changes
Can't build the app in simulator. This review focus on code style.

2021-02-16 21:48 UTC, dannil76 commented on source/containers/Form/hooks/formActions.ts
> + */
Noice words... the function name should tell me enought... please remove comments

2021-02-16 21:48 UTC, dannil76 commented on source/containers/Form/hooks/formActions.ts
> + */
Noice words... see my previous comment :)

2021-02-16 21:48 UTC, dannil76 commented on source/containers/Form/hooks/formActions.ts
> + */
Noice words... see my previous comment :)

2021-02-16 21:48 UTC, dannil76 commented on source/containers/Form/hooks/formReducer.ts
> +    /** Create snapshot of current answers */
Noice words... see my previous comment :)

2021-02-16 21:48 UTC, dannil76 commented on source/containers/Form/hooks/formReducer.ts
> +    /** Restore answers snapshot */
Noice words... see my previous comment :)

2021-02-16 21:48 UTC, dannil76 commented on source/containers/Form/hooks/formReducer.ts
> +    /** Delete answers snapshot */
Noice words... see my previous comment :)

2021-02-16 21:48 UTC, dannil76 commented on source/containers/Form/hooks/useForm.ts
> +   */
Noice words... see my previous comment :)

2021-02-16 21:48 UTC, dannil76 commented on source/containers/Form/hooks/useForm.ts
> +   */
Noice words... see my previous comment :)

2021-02-16 21:48 UTC, dannil76 commented on source/containers/Form/hooks/useForm.ts
> +   */
Noice words... see my previous comment :)

2021-02-17 08:49 UTC, jwinding requested changes
It works as intended, and the code looks really good, nice typescript usage and I like the refactor of the CloseDialog. I made two comments, one very minor about a type, but it's the second one that changes validation behaviour that I think should be changed (or at least discussed, if you have some reasoning about it).

2021-02-17 08:49 UTC, jwinding commented on source/containers/Form/hooks/useForm.ts
> -    dispatch({ type: 'VALIDATE_ANSWER', payload: { answer, id: questionId, checkIfDirty: true } });
Hmm, are you sure this should be removed? This leads to no validation the first time you blur an input field.

2021-02-17 08:51 UTC, jwinding commented on source/components/organisms/Step/CloseDialog/CloseDialog.tsx
> +    color?: 'neutral' | 'blue' | 'red' | 'purple' | 'green';
Okay, you added this back in a fix, nevermind.

2021-02-17 08:52 UTC, jwinding approved these changes

2021-02-17 10:37 UTC, zilaei approved these changes
Looking good! 🎉

2021-02-17 13:42 UTC, merged