(ignore for now) Feat/booking form
helsingborg-stad/app-mitt-helsingborg pull request #574
Opened 2021-11-25 08:21 UTC by sepehrnoor

This line can be removed: Read this short article before you start writing https://www.pullrequest.com/blog/writing-a-great-pull-request-description/

## Explain the changes you’ve made

Good example:
I've added support for authentication to implement Key Result 2 of OKR1. It includes 
model, table, controller and test. For more background, see #CLICKUP-ID.
Include 

## Explain why these changes are made

A good example:
These changes complete the user login and account creation experience. See #CLICKUP_ID for more information.

## Explain your solution

A Good example:
This includes a migration, model and controller for user authentication. 
I'm using Devise to do the heavy lifting. I ran Devise migrations and those are included here.

## How to test the changes?

Concrete example:
1. Checkout this branch
2. Swap the application to run storybook
3. Fire upp the simulator by running the command`yarn ios`
4. ...etc

## Was this feature tested in the following environments?
- [] Storybook on a iOS device/simulator.
- [] Building the Application on a iOS device/simulator.
- [] Building the Application on a Android device/simulator.

## Screenshots (optional)
Screenshots are helpful for UI-related changes. It could be an before and after change as an example.
Even backend code can benefit from a screenshot of the net change.

## Anyhting else? (optional)

A good example:
Let's consider using a 3rd party authentication provider for this, to offload MFA and other considerations as they arise and as the privacy landscape evolves. 
AWS Cognito is a good option, so is Firebase. I'm happy to start researching this path. Let's also consider breaking this out into its own service. 
We can then re-use it or share the accounts with other apps in the future.

2021-11-25 08:22 UTC, sebastianthulin commented
![Quality gate](https://app.embold.io/assets/images/svg/shield-off.svg) Quality gate: **_Failed_** 
 


            
 #### 22 Issues 
* ![Code issue](https://app.embold.io/assets/images/svg/code-issue.svg) 22 Code issues 

 [Details](https://app.embold.io/organization/gh/helsingborg-stad/repositories/fedfce3fd8695f238dea9cb00bd37ce7/pull-request/574)

2021-12-01 13:12 UTC, karlknowit requested changes

2021-12-01 13:12 UTC, karlknowit commented on source/components/molecules/BottomModal/styled.ts
> +  flex-direction: row;
flex-direction : row is default in flex container, only needed if the parent has a flex-direction that is not row

2021-12-01 13:12 UTC, karlknowit commented on source/components/molecules/DateTimeCard/styled.ts
> +  align-items: ${(props) => props.align};
{( { align }) => align}

2021-12-01 13:12 UTC, karlknowit commented on source/screens/bookingScreens/CalendarScreen.tsx
> +const ScrollViewSpacer = styled.View`
OPTIONAL: 

Move styling to its own file

2021-12-02 08:45 UTC, karlknowit requested changes

2021-12-02 08:45 UTC, karlknowit commented on source/components/molecules/CaseCard/CaseCard.tsx
> +  smallDateTimeCard?: boolean;
how about changing the property to `dateTimeCardSize` which is a string of with value "small" or "large" ?

2021-12-02 08:45 UTC, karlknowit commented on source/containers/Form/BookingForm.tsx
> +const ListWrapper = styled.View`
OPTIONAL:

Style in separate file perhaps?

2021-12-02 08:45 UTC, karlknowit commented on source/containers/Form/BookingForm.tsx
> +  const [currentEmail, setCurrentEmail] = useState<string>("");
the explicit type <string> is not needed

2021-12-02 08:59 UTC, sepehrnoor commented on source/screens/bookingScreens/CalendarScreen.tsx
> +  flex-direction: row;
Personally I'd like to keep flex-direction for the sake of clarity.

2021-12-02 09:47 UTC, karlknowit approved these changes

2021-12-02 09:51 UTC, merged