🐛 Make select in editable list scroll properly
helsingborg-stad/app-mitt-helsingborg pull request #580
Opened 2021-12-01 14:43 UTC by Sven65

## Explain the changes you’ve made

I've made a change that stops selects in editable lists from scrolling all the way back up to the top of the page.

## Explain why these changes are made

See #CU-1kxppyf

## Explain your solution

I've added an `onFocus` event to the `RepeaterFieldListItem`.

## How to test

Concrete example:

1. Checkout this branch
2. Start an EKB case
3. Add 2 children when it asks you
4. Focus a text field in the second
5. Change focus to a select menu
6. See that it doesn't scroll to the top anymore

## Tested environments

- [x] Storybook on a iOS device/simulator.
- [] Building the Application on a iOS device/simulator.
- [] Building the Application on a Android device/simulator.

---

## Checklist for reviewers

Here are a few points that are useful for reviewers to check.

The short list of the (maybe) most important points are:

- Does this PR work as expected?
- Does the PR properly only concern a single feature/bug/thing?
- Is the code clear and concise?
- Will the changes impact existing functionality?
- Are there any linting errors (ESLint) that should be resolved?
- Do the automatic GitHub checks pass?

However it is good if a reviewer can be as thorough as possible,
within reasonable limits of course.

### Functionality

- Does this PR work as expected?
- If this is a new feature, does it add value, or is it a sign of feature-creep?
- Will the changes impact existing functionality?
- Does the changes create inconsistencies somewhere else?
- Does the code work on different platforms if applicable?
- How does the code handle if unexpected values are passed to functions etc.?

### Readability, syntax, formatting, style

- Is the code clear and concise?
- Has styling rules (Prettier) been applied to included files?
- Are functions/variables/etc. aptly named?

### Design

- Is the code properly planned and designed?
- Is code organized/separated in a logical fashion?
- Does the code follow clean code practices to a reasonable degree?
- Is the code self-documenting enough?
- Is the code in sync with existing patterns/technologies?
- Does the code reuse existing functionality where applicable?
- Is the code designed with reusability in mind?
- Does the code have hard-coded values that can be refactored?

### Patterns, idioms, tests, best practices

- Are there any linting errors (ESLint) that should be resolved?
- Is the code properly typed (TypeScript)?
- Does the code utilize language features to their full potential?

### Debugging, testing, configuring

- Is appropriate logging used?
- Have tests been added/modified to accommodate the changes?
- Is the feature sufficiently configurable in case tweaks are required in the future?

### Performance, reliability, scalability

- Is the code well optimized?
- Does the code scale?
- Does the code handle failure scenarios?

### Security

- Is there any obvious potential for exploits and security threats?
- Does code check proper authorization where applicable?

### Etiquettes

- Are commits atomic (does only one thing per commit)?
- Does the PR properly only concern a single feature/bug/thing?
- Are commit messages well-written?
- Do the automatic GitHub checks pass?

2021-12-01 14:43 UTC, helsingborgsstad commented
Task linked: [CU-1kxppyf Bugg: select i editable list gör att fokus blir helt fel](https://app.clickup.com/t/1kxppyf)

2021-12-01 14:44 UTC, sebastianthulin commented
![Quality gate](https://app.embold.io/assets/images/svg/shield-check.svg) Quality gate: **_Passed_** 
 


            
 ![No issues](https://app.embold.io/assets/images/svg/check-circle.svg) Everything looks good
 [Details](https://app.embold.io/organization/gh/helsingborg-stad/repositories/fedfce3fd8695f238dea9cb00bd37ce7/pull-request/580)

2021-12-01 15:11 UTC, TeddyAndersson approved these changes
Looks good to me, have not been able to test it though. So might be a good idea to poke someone that has a functional setup of the app :)

2021-12-02 05:21 UTC, karlknowit requested changes

2021-12-02 05:21 UTC, karlknowit commented on source/components/molecules/RepeaterField/RepeaterField.tsx
> +  onFocus?: (e: FocusEvent) => void;
no abbreviations, write event instead of e

2021-12-02 05:21 UTC, karlknowit commented on source/components/molecules/RepeaterField/RepeaterField.tsx
> +  const onInputFocus = (e: FocusEvent) => {
no abbreviations, write event instead of e

2021-12-02 09:12 UTC, karlknowit approved these changes

2021-12-02 09:13 UTC, merged