Partially fix scroll bug again
helsingborg-stad/app-mitt-helsingborg pull request #584
Opened 2021-12-09 09:23 UTC by Sven65

## Explain the changes you’ve made

In accordance with #CU-1kxppyf, I've made a better fix for select scrolling in a form.

## Explain your solution

This solution removes the over-complicated code to calculate scroll positions in favour of a simpler solution that just scrolls to the field itself.

## How to test

Concrete example:

1. Checkout this branch
2. Start a case
3. Add children
4. Click a select box
5. See the scroll works better

## Tested environments

- [] Storybook on a iOS device/simulator.
- [x] Building the Application on a iOS device/simulator.
- [] Building the Application on a Android device/simulator.

## Other notes

While this solution stops the scrolling to top bug, it also makes the bottom content appear under the software keyboard.

---

## Checklist for reviewers

Here are a few points that are useful for reviewers to check.

The short list of the (maybe) most important points are:

- Does this PR work as expected?
- Does the PR properly only concern a single feature/bug/thing?
- Is the code clear and concise?
- Will the changes impact existing functionality?
- Are there any linting errors (ESLint) that should be resolved?
- Do the automatic GitHub checks pass?

However it is good if a reviewer can be as thorough as possible,
within reasonable limits of course.

### Functionality

- Does this PR work as expected?
- If this is a new feature, does it add value, or is it a sign of feature-creep?
- Will the changes impact existing functionality?
- Does the changes create inconsistencies somewhere else?
- Does the code work on different platforms if applicable?
- How does the code handle if unexpected values are passed to functions etc.?

### Readability, syntax, formatting, style

- Is the code clear and concise?
- Has styling rules (Prettier) been applied to included files?
- Are functions/variables/etc. aptly named?

### Design

- Is the code properly planned and designed?
- Is code organized/separated in a logical fashion?
- Does the code follow clean code practices to a reasonable degree?
- Is the code self-documenting enough?
- Is the code in sync with existing patterns/technologies?
- Does the code reuse existing functionality where applicable?
- Is the code designed with reusability in mind?
- Does the code have hard-coded values that can be refactored?

### Patterns, idioms, tests, best practices

- Are there any linting errors (ESLint) that should be resolved?
- Is the code properly typed (TypeScript)?
- Does the code utilize language features to their full potential?

### Debugging, testing, configuring

- Is appropriate logging used?
- Have tests been added/modified to accommodate the changes?
- Is the feature sufficiently configurable in case tweaks are required in the future?

### Performance, reliability, scalability

- Is the code well optimized?
- Does the code scale?
- Does the code handle failure scenarios?

### Security

- Is there any obvious potential for exploits and security threats?
- Does code check proper authorization where applicable?

### Etiquettes

- Are commits atomic (does only one thing per commit)?
- Does the PR properly only concern a single feature/bug/thing?
- Are commit messages well-written?
- Do the automatic GitHub checks pass?

2021-12-09 09:23 UTC, helsingborgsstad commented
Task linked: [CU-1kxppyf Bugg: select i editable list gör att fokus blir helt fel](https://app.clickup.com/t/1kxppyf)

2021-12-09 09:23 UTC, sebastianthulin commented
![Quality gate](https://app.embold.io/assets/images/svg/shield-off.svg) Quality gate: **_Failed_** 
 


            
 #### 4 Issues 
* ![Code issue](https://app.embold.io/assets/images/svg/code-issue.svg) 4 Code issues 

 [Details](https://app.embold.io/organization/gh/helsingborg-stad/repositories/fedfce3fd8695f238dea9cb00bd37ce7/pull-request/584)

2021-12-09 13:15 UTC, MasterKenth requested changes
Doesn't seem to work correctly for me when testing in simulator. ~~Keyboard no longer pops up for text fields and and~~ field focus just scrolls that field so that it is at the top of the screen. Is this intended?

https://user-images.githubusercontent.com/2890987/145402508-d3c6b4c4-6504-4189-8e76-842ca999c3ed.mov

I haven't looked over the code changes yet except for a few minor things.

2021-12-09 13:15 UTC, MasterKenth commented on source/components/organisms/Step/Step.js
> +    console.log("target", e.target);
Should probably remove these 🙂.

2021-12-09 13:15 UTC, MasterKenth commented on source/components/organisms/Step/Step.js
> +    // });
Remove instead of comment-out to avoid bloating the codebase.

2021-12-09 13:15 UTC, MasterKenth commented on source/components/organisms/Step/Step.js
> +        // }}
Same as my other comment; remove instead of comment-out to clean it up 👍

2021-12-09 13:15 UTC, MasterKenth commented on source/containers/FormField/FormField.js
> +  console.log("focusEvent", input.focusEvent);
Remove 👌

2021-12-23 07:02 UTC, Sven65 commented
Closing this as I'll be passing the torch along.

2021-12-23 07:02 UTC, closed without merging