Feat: move bookables to its own context
helsingborg-stad/app-mitt-helsingborg pull request #590
Opened 2021-12-13 10:52 UTC by karlknowit

This line can be removed: Read this short article before you start writing https://www.pullrequest.com/blog/writing-a-great-pull-request-description/

## Explain the changes you’ve made
Fetching bookables (i.e. services that a resident can book) is moved to its own context.

## Explain why these changes are made
In order to not fetch bookables every time the bottom modal is opened, and to have data stored till the application is closed/terminated, the fetching is moved to its own context.

## Explain your solution
Created a new context which is used in the ServiceSelection screen. Did use the isDevMode variables from AppContext context in order to only try to fetch bookables when in development mode since the bookingservice is not in production.

## How to test

1. Checkout this branch
2. Fire upp the simulator by running the command `yarn ios`
3. Change the APP_ENV environment variable and check if bookables are fetched or not.

## Tested environments

- [] Storybook on a iOS device/simulator.
- [x] Building the Application on a iOS device/simulator.
- [] Building the Application on a Android device/simulator.

2021-12-13 10:53 UTC, sebastianthulin commented
![Quality gate](https://app.embold.io/assets/images/svg/shield-off.svg) Quality gate: **_Failed_** 
 


            
 #### 1 Issues 
* ![Code issue](https://app.embold.io/assets/images/svg/code-issue.svg) 1 Code issues 

 [Details](https://app.embold.io/organization/gh/helsingborg-stad/repositories/fedfce3fd8695f238dea9cb00bd37ce7/pull-request/590)

2021-12-27 08:55 UTC, Sven65 requested changes

2021-12-27 08:55 UTC, Sven65 commented on source/screens/featureModalScreens/ServiceSelection.tsx
> +        const contacts = [];
Missing a type on this array

2021-12-27 09:35 UTC, Sven65 commented
Tested according to instructions provided using the latest `booking-api` in sls-api.
Request fails with a response of

```
Authorization header requires 'Credential' parameter. Authorization header requires 'Signature' parameter. Authorization header requires 'SignedHeaders' parameter. Authorization header requires existence of either a 'X-Amz-Date' or a 'Date' header. Authorization=[...]
```

2022-01-20 08:46 UTC, sepehrnoor approved these changes
Looks good to me.

2022-01-20 15:21 UTC, sepehrnoor approved these changes
Discussed with Karl and approved.

2022-01-21 05:15 UTC, merged