Feat/show completion submitted in case summary
helsingborg-stad/app-mitt-helsingborg pull request #631
Opened 2022-01-25 15:23 UTC by karlknowit

## Explain the changes you’ve made
Added support for the new case status type `active:completion:submitted` in CaseSummary.tsx file

## Explain why these changes are made
In order to display to the user that its completions has been submitted, this new status type is added.

## Explain your solution
The new status type is added to the `ApplicationStatusType` enum, this enum is the used in CaseSummary.tsx file where we change the button text accordingly.

## How to test

1. Checkout this branch
2. Fire upp the simulator by running the command `yarn ios`
3. Make sure you have a case with the status type of `active:completion:submitted`

## Tested environments

- [] Storybook on a iOS device/simulator.
- [x] Building the Application on a iOS device/simulator.
- [] Building the Application on a Android device/simulator.

## Screenshots

![simulator_screenshot_0BA4AE5A-695D-4AB9-963F-814BE077EC6C](https://user-images.githubusercontent.com/81250970/151005428-02e5a7da-7e22-438d-a746-d340a1c79cc8.png)

2022-01-25 15:23 UTC, helsingborgsstad commented
Task linked: [CU-1n07crv Logik som hanterar ny statustyp för 'Detaljvyn'](https://app.clickup.com/t/1n07crv)

2022-01-25 16:48 UTC, dannil76 requested changes

2022-01-25 16:48 UTC, dannil76 commented on source/screens/caseScreens/CaseSummary.tsx
> +  ACTIVE_COMPLETION_SUBMITTED,
We need to add `ACTIVE_RANDOM_CHECK_SUBMITTED` as well. This is the good old 'Stickprovskontroll'

2022-01-27 11:58 UTC, dannil76 approved these changes
OK, assuming you have it under control. :)

2022-01-31 13:50 UTC, MasterKenth approved these changes

2022-02-01 06:33 UTC, merged