Bug/reopen form issue
helsingborg-stad/app-mitt-helsingborg pull request #640
Opened 2022-02-08 15:58 UTC by karlknowit

## Explain the changes you’ve made
Fixed a bug where opening a form a second time would cause the app to only show a loading spinner. This is due to that the application, after a form has been closed, saves the case with encrypted answers in application state, which we don't decrypt, causing the logic to fail.

The solution was to save the answers unencrypted in the application state to be able to show the form again.
Also added a modal telling the user that an update is ongoing when trying to close the form, this is to make sure that we have the same data in backend as in the application state.
Also added a modal if something goes wrong when closing the form.

## Explain why these changes are made
A user needs to be able to open the form more than once without experiencing any errors. And we also want the same data in backend as in the application state.

## Explain your solution

## How to test

**Successful case update**

1. Checkout this branch
2. Fire upp the simulator by running the command `yarn ios` or `yarn android`
3. Open a case in the application
4. Do changes in the form and close it. At least one modal should appear
5. If successful updating the case, open it again and check if values you entered before are still there.

**Unsuccessful case update**

1. Checkout this branch
2. Fire upp the simulator by running the command `yarn ios` or `yarn android`
3. Make sure (either in application or backend) that updating a case will fail
4. Open a case in the application
5. Do changes in the form and close it. An error modal should appear

## Tested environments

- [] Storybook on a iOS device/simulator.
- [x] Building the Application on a iOS device/simulator.
- [x] Building the Application on a Android device/simulator.

## Screenshots

 **Iphone:**
![simulator_screenshot_B38B32AD-9724-4654-B444-B9A1F4C5BC60](https://user-images.githubusercontent.com/81250970/153140008-8857866a-d2dd-4363-9cb1-ebbbb51e6690.png)

![simulator_screenshot_3FC196D5-65D1-4E63-A680-05EDD5104354](https://user-images.githubusercontent.com/81250970/153140524-25cdf657-bf11-456d-9c3d-82b6f7731fce.png)

**Android:**

2022-02-10 08:03 UTC, jlarsson approved these changes
Nice work with converting to TS, renaming and somewhat pinpointing reasonable next steps in refinement.

2022-02-11 07:32 UTC, helsingborgsstad commented
Task linked: [CU-1u6383f Bugg: FormCaseScreen visar ibland bara en loadingspinner när den ska visa formulär](https://app.clickup.com/t/1u6383f)

2022-02-15 16:21 UTC, MasterKenth requested changes

2022-02-15 16:21 UTC, MasterKenth commented on source/containers/Form/Form.tsx
> +  [UPDATE_CASE_STATE.PENDING]: {
I think it would be more appropriate to rename this from `PENDING` to `IDLE`.

2022-02-16 08:36 UTC, MasterKenth approved these changes

2022-02-16 08:37 UTC, merged