Feat/encryption system rework with password
helsingborg-stad/app-mitt-helsingborg pull request #656
Opened 2022-03-03 15:09 UTC by MasterKenth

## Explain the changes you’ve made
* Added a new encryption system that works with abstract "strategies" for encryption and decryption.
  * Two strategies are included; DeviceLocal (same as old "private AES" used for solo applicants), and Password-based (will replaced Symmetric Key)
* Deprecated existing encryption service and helper

Note: new encryption system is not being used by anything in this PR. Old encryption service is still being used.

## Explain why these changes are made

The current encryption system is not extensible enough and making changes are hard. This PR change was needed to facilitate implementing Password-based encryption ("pin code") as well as preparing to remove Symmetric Key exchange encryption.

## Explain your solution

Broadly two things have happened:

* The now deprecated `EncryptionService` and `EncryptionHelper` has been moved to `source/services/encryption/DEPRECATED` and files using them has been updated to point there (`CaseOverview` etc.).
* New files has been added to `source/services/encryption` that implements the new system, that are not used by anything yet.

### The new encryption system
Each method of encryption implements `IEncryptionStrategy`. They are oblivious to project-specific data structures (`Case`, `Form` etc.) and work only with raw data and abstract interfaces.

`CaseEncryptionService` is the glue between the generic strategies and the project-specific data. It handles encryption/decryption based on `Case` objects and `Form` objects. This is generally the class that will be called on by the UI layer or contexts.

`CaseEncryptionHelper` includes a set of commonly used types and functions as well as manages the mapping between `Case` encryption type and concrete encryption strategy (might move the second part to a separate concern?).

## How to test

Concrete example:

1. Checkout this branch
2. Make sure tests pass
3. Make sure app works as usual (start new case, encrypt ongoing, submit etc.)

## Tested environments

- [] Storybook on a iOS device/simulator.
- [x] Building the Application on a iOS device/simulator.
- [] Building the Application on a Android device/simulator.

## Screenshots

## Other notes

---

## Checklist for reviewers

Here are a few points that are useful for reviewers to check.

The short list of the (maybe) most important points are:

- Does this PR work as expected?
- Does the PR properly only concern a single feature/bug/thing?
- Is the code clear and concise?
- Will the changes impact existing functionality?
- Are there any linting errors (ESLint) that should be resolved?
- Do the automatic GitHub checks pass?

However it is good if a reviewer can be as thorough as possible,
within reasonable limits of course.

### Functionality

- Does this PR work as expected?
- If this is a new feature, does it add value, or is it a sign of feature-creep?
- Will the changes impact existing functionality?
- Does the changes create inconsistencies somewhere else?
- Does the code work on different platforms if applicable?
- How does the code handle if unexpected values are passed to functions etc.?

### Readability, syntax, formatting, style

- Is the code clear and concise?
- Has styling rules (Prettier) been applied to included files?
- Are functions/variables/etc. aptly named?

### Design

- Is the code properly planned and designed?
- Is code organized/separated in a logical fashion?
- Does the code follow clean code practices to a reasonable degree?
- Is the code self-documenting enough?
- Is the code in sync with existing patterns/technologies?
- Does the code reuse existing functionality where applicable?
- Is the code designed with reusability in mind?
- Does the code have hard-coded values that can be refactored?

### Patterns, idioms, tests, best practices

- Are there any linting errors (ESLint) that should be resolved?
- Is the code properly typed (TypeScript)?
- Does the code utilize language features to their full potential?

### Debugging, testing, configuring

- Is appropriate logging used?
- Have tests been added/modified to accommodate the changes?
- Is the feature sufficiently configurable in case tweaks are required in the future?

### Performance, reliability, scalability

- Is the code well optimized?
- Does the code scale?
- Does the code handle failure scenarios?

### Security

- Is there any obvious potential for exploits and security threats?
- Does code check proper authorization where applicable?

### Etiquettes

- Are commits atomic (does only one thing per commit)?
- Does the PR properly only concern a single feature/bug/thing?
- Are commit messages well-written?
- Do the automatic GitHub checks pass?

2022-03-03 15:16 UTC, helsingborgsstad commented
Task linked: [CU-21w373e Implementera kryptering med lösenord/pinkod](https://app.clickup.com/t/21w373e)

2022-03-07 13:51 UTC, karlknowit requested changes

2022-03-07 13:51 UTC, karlknowit commented on source/services/encryption/DeviceLocalAESStrategy.ts
> +  const key = await Aes.pbkdf2(randomBytes, "salt4D42bf960Sm1", 5000, 256);
I suggest that values like `"salt4D42bf960Sm1", 5000, 256` are put in constants for readability

2022-03-07 13:51 UTC, karlknowit commented on source/services/encryption/PasswordStrategy.ts
> +  const key = await Aes.pbkdf2(password, "salt4D42bf960Sm1", 5000, 256);
As mentioned above, put in constants. These values are also in multiple places which makes it even better to have those in constants.

2022-03-07 13:51 UTC, karlknowit commented on source/services/encryption/test/CaseEncryptionService.test.ts
> +function MakeMockCase(
MakeMockCase -> makeMockCase

2022-03-07 13:51 UTC, karlknowit commented on source/services/encryption/test/CaseEncryptionService.test.ts
> +    const form = getCurrentForm(CASE_DECRYPTED_SOLO);
missing newline before expect in some tests

2022-03-07 13:51 UTC, karlknowit commented on source/services/encryption/test/CaseEncryptionService.test.ts
> +    expect(firstCheck).toEqual(false);
`toEqual` -> `toBe` for primitive values

2022-03-07 13:51 UTC, karlknowit commented on source/services/encryption/test/CaseEncryptionService.test.ts
> +    expect(encryption.type).toEqual(EncryptionType.PASSWORD);
toEqual -> toBe

2022-03-07 13:51 UTC, karlknowit commented on source/services/encryption/test/CaseEncryptionService.test.ts
> +    expect(typeof password).toEqual("string");
toEqual -> toBe

2022-03-07 13:51 UTC, karlknowit commented on source/services/encryption/test/CaseEncryptionService.test.ts
> +    expect(password).toEqual(testPassword);
toEqual -> toBe

2022-03-07 13:51 UTC, karlknowit commented on source/services/encryption/test/CaseEncryptionService.test.ts
> +    expect((decryptError as EncryptionException).status).toEqual(
toEqual -> toBe

2022-03-07 15:35 UTC, MasterKenth commented on source/services/encryption/CaseEncryptionHelper.ts
> +  const newAnswers: Answer[] = JSON.parse(decryptedData);
Good call; I've added a check and test for that.

2022-03-07 15:38 UTC, MasterKenth commented on source/services/encryption/CaseEncryptionHelper.ts
> +export function getEncryptionFromCase(caseData: Case): EncryptionDetails {
In practice probably not, however the next few lines check for that so it should be ok (or at least possible to handle):

```typescript
  if (!caseData) {
    throw new EncryptionException(
      EncryptionErrorStatus.INVALID_CASE,
      "invalid case"
    );
  }
```

2022-03-08 09:55 UTC, sebastianthulin commented
![Quality gate](https://app.embold.io/assets/images/svg/shield-check.svg) Quality gate: **_Passed_** 
 


            
 #### 2 Issues 
* ![Anti-pattern](https://app.embold.io/assets/images/svg/anti-pattern.svg) 2 Anti-patterns 

 [Details](https://app.embold.io/organization/gh/helsingborg-stad/repositories/fedfce3fd8695f238dea9cb00bd37ce7/pull-request/656)

2022-03-08 11:47 UTC, karlknowit approved these changes

2022-03-08 12:16 UTC, merged