Add space between fields in form
helsingborg-stad/app-mitt-helsingborg pull request #689
Opened 2022-05-06 08:15 UTC by Sven65

## Explain the changes you’ve made

I've added a spacer between the title of a field and the field itself.

## Explain why these changes are made

See #CU-2qa0m9m

## Explain your solution

Added a simple spacer component

## How to test

Concrete example:

1. Checkout this branch
2. Start a form
3. See that there's more space between components

## Tested environments

- [] Storybook on a iOS device/simulator.
- [x] Building the Application on a iOS device/simulator.
- [] Building the Application on a Android device/simulator.

## Screenshots

Before:
![Simulator Screen Shot - iPhone 12 - 2022-05-06 at 10 14 30](https://user-images.githubusercontent.com/10225982/167093847-34d038c7-b305-4be7-a70a-87ee8e792a1b.png)

After:

![Simulator Screen Shot - iPhone 12 - 2022-05-06 at 10 14 18](https://user-images.githubusercontent.com/10225982/167093872-d7d7b1bd-b996-46fe-b4dd-5f0672b82341.png)

---

## Checklist for reviewers

Here are a few points that are useful for reviewers to check.

The short list of the (maybe) most important points are:

- Does this PR work as expected?
- Does the PR properly only concern a single feature/bug/thing?
- Is the code clear and concise?
- Will the changes impact existing functionality?
- Are there any linting errors (ESLint) that should be resolved?
- Do the automatic GitHub checks pass?

However it is good if a reviewer can be as thorough as possible,
within reasonable limits of course.

### Functionality

- Does this PR work as expected?
- If this is a new feature, does it add value, or is it a sign of feature-creep?
- Will the changes impact existing functionality?
- Does the changes create inconsistencies somewhere else?
- Does the code work on different platforms if applicable?
- How does the code handle if unexpected values are passed to functions etc.?

### Readability, syntax, formatting, style

- Is the code clear and concise?
- Has styling rules (Prettier) been applied to included files?
- Are functions/variables/etc. aptly named?

### Design

- Is the code properly planned and designed?
- Is code organized/separated in a logical fashion?
- Does the code follow clean code practices to a reasonable degree?
- Is the code self-documenting enough?
- Is the code in sync with existing patterns/technologies?
- Does the code reuse existing functionality where applicable?
- Is the code designed with reusability in mind?
- Does the code have hard-coded values that can be refactored?

### Patterns, idioms, tests, best practices

- Are there any linting errors (ESLint) that should be resolved?
- Is the code properly typed (TypeScript)?
- Does the code utilize language features to their full potential?

### Debugging, testing, configuring

- Is appropriate logging used?
- Have tests been added/modified to accommodate the changes?
- Is the feature sufficiently configurable in case tweaks are required in the future?

### Performance, reliability, scalability

- Is the code well optimized?
- Does the code scale?
- Does the code handle failure scenarios?

### Security

- Is there any obvious potential for exploits and security threats?
- Does code check proper authorization where applicable?

### Etiquettes

- Are commits atomic (does only one thing per commit)?
- Does the PR properly only concern a single feature/bug/thing?
- Are commit messages well-written?
- Do the automatic GitHub checks pass?

2022-05-06 08:15 UTC, helsingborgsstad commented
Task linked: [CU-2qa0m9m Avstånd mellan komponenter och rubriker är för litet](https://app.clickup.com/t/2qa0m9m)

2022-05-11 07:15 UTC, kajm requested changes

2022-05-11 07:15 UTC, kajm commented on source/containers/FormField/FormField.tsx
> +        </>
It is a little weird using a Text component for spacing, how about making a label container instead?
```js

const LabelContainer = styled.View`
width: 100%;
padding-bottom: 16px;
`;

<LabelContainer>
          <Label
            colorSchema={validColorSchema}
            underline={labelLine}
            help={
              !input.helpInComponent && help && Object.keys(help).length > 0
                ? help
                : {}
            }
          >
            {label}
          </Label>
        </LabelContainer>
```

2022-05-12 12:42 UTC, dannil76 approved these changes

2022-05-12 12:49 UTC, MasterKenth approved these changes

2022-05-13 07:38 UTC, merged