bug: Wrong month showed in case card
helsingborg-stad/app-mitt-helsingborg pull request #702
Opened 2022-05-20 11:13 UTC by kajm

## Explain the changes you’ve made
The end date (month) for when a period were ending were taken from the wrong property, resulting in wrong month were showed in a case card.

## Explain why these changes are made
The old period end date property did specify an end date on the wrong month. Example:

Lets say that the period did end at the end of march, the old property value would then say that the end date is 1 of april, which is kinda true. But then the period in the case card would say the wrong month.
The new end date property does instead end the period of 31 of march, resulting in correct month is showed to the user.

## Explain your solution
Changing the preferred property to take date from 

## How to test

1. Checkout this branch
2. Fire upp the simulator by running the command `yarn ios` or `yarn android`
3. Have a recurring case and check that the period is showed correct in the case card

## Tested environments

- [] Storybook on a iOS device/simulator.
- [x] Building the Application on a iOS device/simulator.
- [] Building the Application on a Android device/simulator.

2022-05-20 11:13 UTC, helsingborgsstad commented
Task linked: [CU-2rxe4tn Bugg: Appen visar fel månad för en period](https://app.clickup.com/t/2rxe4tn)

2022-05-23 12:31 UTC, dannil76 requested changes

2022-05-23 12:31 UTC, dannil76 commented on source/screens/caseScreens/CaseOverview.tsx
> +    period?.endDate ?? application?.periodenddate;
application?.periodenddate kommer att tas bort från caset i framtiden. Kanske onödig att ha med detta då?

2022-05-24 09:17 UTC, MasterKenth approved these changes

2022-05-24 10:34 UTC, merged