Feat/co applicant modal
helsingborg-stad/app-mitt-helsingborg pull request #705
Opened 2022-06-08 07:22 UTC by kajm

## Explain the changes you’ve made
Added the ability to add a co applicant when opening a new application

## Explain why these changes are made
A user needs to be able to add a co applicant when applying for a new application, and to make our work easier, we want the co applicant to be added on a case before the case is opened, hence these changes are made.

## Explain your solution
Added two new modals, one for opening a form and/or opening the add co applicant modal, and the addCoApplicant modal for entering a personal number for the co applicant.

Added API for adding a new co applicant.

## How to test

1. Checkout this branch
2. Fire upp the simulator by running the command `yarn ios` or `yarn android`
3. Make sure you have a new application case in backend
4. Start a new application

## Tested environments

- [x] Storybook on a iOS device/simulator.
- [] Building the Application on a iOS device/simulator.
- [] Building the Application on a Android device/simulator.

## Screenshots
![simulator_screenshot_512D43D7-EA83-45B4-8553-B63B170DA7E6](https://user-images.githubusercontent.com/9610681/172556369-4c0aa279-bbaf-471d-92f4-9d58bd636bf5.png)

![simulator_screenshot_C4D15653-126B-47FA-A240-A6B5C4F43B4F](https://user-images.githubusercontent.com/9610681/172556406-7cc80d01-063d-4392-9f2c-f01e9aa24ead.png)

2022-06-08 07:29 UTC, helsingborgsstad commented
Task linked: [CU-2q9vhfg Skapa ny modal med input-funktion i appen](https://app.clickup.com/t/2q9vhfg)

2022-06-08 13:04 UTC, MasterKenth requested changes
(I haven't tested that pin/other modals still work.)

2022-06-08 15:55 UTC, kajm commented on source/components/atoms/TextButton/TextButton.tsx
> +interface TextButtonProps {
Do we need to export something that isn't used by anything else?

2022-06-09 10:59 UTC, kajm commented on source/components/organisms/AddCoApplicantModal/AddCoApplicantModal.tsx
> +interface AddCoApplicantContentProps {
Same question as above

2022-06-09 11:03 UTC, kajm commented on source/components/organisms/StartNewApplicationModal/StartNewApplicationModal.tsx
> +export default function StartNewApplicationModal({
I dont have a better name than the one you suggested. Lets start with that one

2022-06-10 06:12 UTC, kajm commented
> 



> (I haven't tested that pin/other modals still work.)

Me neither. I need help testing that before this PR can be merged

2022-06-10 06:12 UTC, kajm commented
> 



> (I haven't tested that pin/other modals still work.)

Me neither. I need help testing that before this PR can be merged

2022-06-13 07:18 UTC, dannil76 approved these changes
It works

2022-06-13 08:16 UTC, MasterKenth requested changes

2022-06-13 08:35 UTC, kajm commented on source/components/organisms/AddCoApplicantModal/AddCoApplicantModal.tsx
>      <Modal
Not actually using it. But will add it so the warning will disappear.

2022-06-14 08:11 UTC, merged