Feat/required property filepicker
helsingborg-stad/app-mitt-helsingborg pull request #717
Opened 2022-06-27 04:59 UTC by kajm

## Explain the changes you’ve made
Updated the FilePicker component to handle required property from form builder.

## Explain why these changes are made
There is a need to force users to upload files in the form

## Explain your solution
Updated the filepicker component to use the error property and to show an error message if the required property is set in the form.

## How to test

Concrete example:

1. Checkout this branch
2. Fire upp the simulator by running the command `yarn ios` or `yarn android`
3. Make sure you run form builder with these changes: https://github.com/helsingborg-stad/mitt-helsingborg-form-builder/pull/66
4. Make sure you have a FilePicker with the required property set
5. Run the application and run the form mentioned above

## Tested environments

- [] Storybook on a iOS device/simulator.
- [x] Building the Application on a iOS device/simulator.
- [] Building the Application on a Android device/simulator.

2022-06-27 04:59 UTC, helsingborgsstad commented
Task linked: [CU-21grhrq Lägg till funktionalitet i app som tvingar användarna att ladda upp bild/fil](https://app.clickup.com/t/21grhrq)

2022-06-28 12:16 UTC, MasterKenth requested changes

2022-06-28 12:16 UTC, MasterKenth commented on source/components/molecules/FilePicker/FilePicker.stories.tsx
> +import { File, FileType } from "./FilePicker.types";
Use `import type {...}` ✌️

2022-06-28 12:16 UTC, MasterKenth commented on source/components/molecules/FilePicker/test/FilePicker.test.tsx
> +import { FileType, ErrorValidation } from "../FilePicker.types";
`import type`

2022-06-28 12:30 UTC, MasterKenth requested changes
fyfaen

2022-06-28 12:30 UTC, merged