Feat/debug info screen
helsingborg-stad/app-mitt-helsingborg pull request #761
Opened 2022-09-01 08:30 UTC by MasterKenth

## Explain the changes you’ve made

Added a debug info screen.

## Explain why these changes are made

Useful for debugging.

## Explain your solution

Added a new screen similar in structure to the dev features screen. It can be accessed from the profile screen. It gathers information from different sources (currently system info and storage info but is extensible). 

## How to test

Concrete example:

1. Checkout this branch
2. Launch
3. Go to profile screen and click "Felsökningsinformation"
4. Verify things work

## Tested environments

- [] Storybook on a iOS device/simulator.
- [x] Building the Application on a iOS device/simulator.
- [x] Building the Application on a Android device/simulator.

## Screenshots

![image](https://user-images.githubusercontent.com/2890987/187869398-cfb96131-1e51-4223-933f-ca3aab308012.png)

---

## Checklist for reviewers

Here are a few points that are useful for reviewers to check.

The short list of the (maybe) most important points are:

- Does this PR work as expected?
- Does the PR properly only concern a single feature/bug/thing?
- Is the code clear and concise?
- Will the changes impact existing functionality?
- Are there any linting errors (ESLint) that should be resolved?
- Do the automatic GitHub checks pass?

However it is good if a reviewer can be as thorough as possible,
within reasonable limits of course.

### Functionality

- Does this PR work as expected?
- If this is a new feature, does it add value, or is it a sign of feature-creep?
- Will the changes impact existing functionality?
- Does the changes create inconsistencies somewhere else?
- Does the code work on different platforms if applicable?
- How does the code handle if unexpected values are passed to functions etc.?

### Readability, syntax, formatting, style

- Is the code clear and concise?
- Has styling rules (Prettier) been applied to included files?
- Are functions/variables/etc. aptly named?

### Design

- Is the code properly planned and designed?
- Is code organized/separated in a logical fashion?
- Does the code follow clean code practices to a reasonable degree?
- Is the code self-documenting enough?
- Is the code in sync with existing patterns/technologies?
- Does the code reuse existing functionality where applicable?
- Is the code designed with reusability in mind?
- Does the code have hard-coded values that can be refactored?

### Patterns, idioms, tests, best practices

- Are there any linting errors (ESLint) that should be resolved?
- Is the code properly typed (TypeScript)?
- Does the code utilize language features to their full potential?

### Debugging, testing, configuring

- Is appropriate logging used?
- Have tests been added/modified to accommodate the changes?
- Is the feature sufficiently configurable in case tweaks are required in the future?

### Performance, reliability, scalability

- Is the code well optimized?
- Does the code scale?
- Does the code handle failure scenarios?

### Security

- Is there any obvious potential for exploits and security threats?
- Does code check proper authorization where applicable?

### Etiquettes

- Are commits atomic (does only one thing per commit)?
- Does the PR properly only concern a single feature/bug/thing?
- Are commit messages well-written?
- Do the automatic GitHub checks pass?

2022-09-01 08:31 UTC, helsingborgsstad commented
Task linked: [CU-3cy7q1e Lägg till vy med felsökningsinformation](https://app.clickup.com/t/3cy7q1e)

2022-09-02 07:46 UTC, kajm requested changes

2022-09-02 07:46 UTC, kajm commented on source/hooks/useAsync.ts
> +  const [isLoading, setIsLoading] = useState(true);
Perhaps the asyncFunction should be a state instead. By doing this we avoid that the asyncFunction is re-triggered when the function is changed outside this hook.

2022-09-02 07:46 UTC, kajm commented on source/screens/debugInfoScreen/DebugInfoScreen.styled.ts
> +  padding-left: 16px;
```js
margin: 16px 16px 40px 16px;
```

2022-09-02 07:46 UTC, kajm commented on source/screens/debugInfoScreen/DebugInfoScreen.tsx
> +
reorder imports?

2022-09-02 07:46 UTC, kajm commented on source/screens/debugInfoScreen/DebugInfoScreen.tsx
> +}
no type file for this one?

2022-09-02 07:46 UTC, kajm commented on source/screens/debugInfoScreen/DebugInfoScreen.tsx
> +        {debugInfo && (
**OPTIONAL**

Create a new component called DebugInfo and make that component decide to render content or not. By doing this we can avoid checks like:

```js
{debugInfo && ... }
```

2022-09-05 12:07 UTC, kajm requested changes

2022-09-05 12:07 UTC, kajm commented on source/components/organisms/DebugInfo/DebugInfo.tsx
> +
if (!debugInfo) return null;

2022-09-05 12:28 UTC, kajm requested changes

2022-09-05 12:28 UTC, kajm commented on source/components/organisms/DebugInfo/DebugInfo.styled.ts
> +  margin-top: 16px;
```js
margin: 16px 24px 0px 24px;
```

2022-09-05 12:28 UTC, kajm commented on source/components/organisms/DebugInfo/DebugInfo.styled.ts
> +  margin-top: 2px;
```js
margin: 2px 0px;
```

2022-09-05 12:28 UTC, kajm commented on source/components/organisms/DebugInfo/DebugInfo.styled.ts
> +  margin-top: 8px;
```js
margin: 8px 0px;
```

2022-09-05 12:28 UTC, kajm commented on source/components/organisms/DebugInfo/DebugInfo.test.tsx
> +});
Don't we want a test when we actually render something?

2022-09-05 12:28 UTC, kajm commented on source/components/organisms/DebugInfo/DebugInfo.tsx
> +import { Text } from "../../atoms";
add newline

2022-09-05 12:28 UTC, kajm commented on source/components/organisms/DebugInfo/DebugInfo.tsx
> +              ))}
**OPTIONAL**
Removing `category.entries &&` 

```js
              (category?.entries ?? []).map((entry) => (
                <CategoryEntry key={`${category.name}-${entry.name}`}>
                  <CategoryEntryName>{entry.name}</CategoryEntryName>
                  <CategoryEntryValue>{entry.value}</CategoryEntryValue>
                </CategoryEntry>
              ))
```

2022-09-05 12:28 UTC, kajm commented on source/screens/debugInfoScreen/DebugInfoScreen.styled.ts
> +  margin-bottom: 8px;
```js
margin: 8px 0px
```

2022-09-05 12:28 UTC, kajm commented on source/screens/debugInfoScreen/DebugInfoScreen.tsx
> +          }}
Move this function to a constant instead. And also, the function should not be `async`

```js
const handleBackButtonClick(press = () => {
  navigation.navigate("App");
};
...
      <MarginButton
          block
          variant="contained"
          colorSchema="neutral"
          onClick={handleBackButtonClick}
```

2022-09-05 13:12 UTC, kajm approved these changes
Borken, but it wörks

2022-09-05 13:13 UTC, merged