feat: remove disallowed sentry event properties
helsingborg-stad/app-mitt-helsingborg pull request #781
Opened 2022-10-04 13:04 UTC by kajm

## Explain the changes you’ve made
Remove event properties that is considered as personal information

## Explain why these changes are made
We don't need user specific data when troubleshooting, hence removing it.

## Explain your solution
Specify an array of paths in the Sentry.Event object where user data is. Use lodash set to set a new undefined value on that specific path.

1. Checkout this branch
2. Fire upp the simulator by running the command `yarn ios` or `yarn android`
3. Make the array send data to sentry by throw in app.tsx as an example

## Tested environments

- [] Storybook on a iOS device/simulator.
- [x] Building the Application on a iOS device/simulator.
- [] Building the Application on a Android device/simulator.

2022-10-04 13:07 UTC, helsingborgsstad commented
Task linked: [CU-3hdexwf Ladda inte upp information till Sentry som inte är nödvändig för felsökning](https://app.clickup.com/t/3hdexwf)

2022-10-05 12:53 UTC, MasterKenth requested changes
Does not work as intended. beforeSend doesn't seem to recieve an event with device data, so after scrubbing it goes from `"contexts": {}` to `"contexts": { "device": {} }` which I suspect overrides _all_ device info afterwards, since the device tab for the event in Sentry now is completely empty.

2022-10-05 12:56 UTC, MasterKenth commented on source/services/monitoring/SentryMonitoringService.ts
> +          eventCopy = setObjectPathValue(eventCopy, path, undefined);
Potentially move to using a specific "unset" function instead.

2022-10-05 14:25 UTC, MasterKenth requested changes

2022-10-05 14:25 UTC, MasterKenth commented on source/services/monitoring/SentryMonitoringService.ts
> +          filteredEvent = unsetObjectPathValue<Sentry.Event>(event, path);
Template parameter `<Sentry.Entry>` is superfluous - type can be inferred.

2022-10-05 14:34 UTC, MasterKenth approved these changes

2022-10-06 05:52 UTC, dannil76 requested changes

2022-10-06 05:52 UTC, dannil76 commented on source/services/monitoring/SentryMonitoringService.ts
> +const forbiddenSentryEventProperties = [
Är det kanske lättare att tänka strikt så att vi väljer de vi VILL tillåta. Kanske kan bli jobbigt att veta på förhand alla som vi inte vill ha med?

2022-10-06 08:36 UTC, closed without merging