fix: retry submit signed cases
helsingborg-stad/app-mitt-helsingborg pull request #827
Opened 2022-11-22 16:02 UTC by MasterKenth

## Explain the changes you’ve made

Added a check when fetching for cases that should be submitted (fully signed) and try to re-submit them.

## Explain why these changes are made

Fixes potential issue where if decrypting or submission of form (see diagram below, step 3 and 4) the case would appear submitted (or "signed") but not actually submitted. This fix attempts to identify and re-submit those cases during case fetching.

## Explain your solution

Added function during `fetchCases` that checks for the problematic cases, and add another function to (re)submit them (also during `fetchCases`).

Additionally moved some parts in `CaseActions` around for better structure, and fixed some linting/error handling issues. 

## How to test

Concrete example:

1. Checkout this branch
2. Run through a form until sign
3. Simulate a problem after signing (for example throwing an error in `FormCaseScreen` line 110)
4. Verify that the case (in dynamo) is now signed but still encrypted
5. Exit the form and verify it says "signerad"
6. Refresh and verify that it was re-submitted and is now "inskickad"

## Tested environments

- [] Storybook on a iOS device/simulator.
- [x] Building the Application on a iOS device/simulator.
- [] Building the Application on a Android device/simulator.

## Screenshots

Sequence diagram:
```mermaid
sequenceDiagram
    App->>Api: 1) UpdateCase (sign)
    note right of Api: (answers encrypted)
    Api->>App: 2) fully signed (SIGNATURE_COMPLETED)
    App->>App: 3) decrypt answers
    App->>Api: 4) UpdateCase (unencrypted/submit)
    note right of Api: (answers unencrypted)
```

2022-11-22 16:02 UTC, helsingborgsstad commented
Task linked: [CU-3terp47 Bugg: ansökan är signerad men svaren är fortfarande krypterade och kan inte skickas in](https://app.clickup.com/t/3terp47)

2022-11-23 12:06 UTC, kajm requested changes

2022-11-23 12:06 UTC, kajm commented on source/helpers/test/promise.test.tsx
> +      const promises: Promise<number | string>[] = [
As discussed, you can use your own functions for objects with status and value.

2022-11-23 12:06 UTC, kajm commented on source/store/actions/CaseActions.ts
>      };
This can be refactored to:

```js
const newCase = response.data.data.attributes;
```

2022-11-23 13:18 UTC, kajm approved these changes

2022-11-23 13:19 UTC, merged