fix(formcasescreen): fetch encrytion before opening form
helsingborg-stad/app-mitt-helsingborg pull request #837
Opened 2022-12-15 12:25 UTC by kajm

## Explain the changes you’ve made
Make sure that the encryption is set before opening the form.

## Explain why these changes are made
The form were opened before the encryption pin were set in state, which meant that the useForm hook were setting an initial state without the encryption pin. This meant that there were no encryption bin to show to the user at the end of the form.

## Explain your solution
Added a loading state and an activity indicator which tricks the user that the form is loading when it actually only sets the encryption pin in the state. By doing this we ensure that the pin is loaded (and hopefully exist) before opening the form and sets the initial state in the useForm hook.

Concrete example:

1. Checkout this branch
2. Fire upp the simulator by running the command `yarn ios` or `yarn android`
3. Run a form where there is both an applicant and co-applicant, like an ongoing form
4. Make sure the encryption pin is shown at the end of the form, after sign

## Tested environments

- [] Storybook on a iOS device/simulator.
- [x] Building the Application on a iOS device/simulator.
- [] Building the Application on a Android device/simulator.

## Screenshots

<img width="397" alt="Pasted Graphic" src="https://user-images.githubusercontent.com/9610681/207858708-a2dbfd80-2e3a-4809-b8f7-4edce2cef881.png">

2022-12-15 12:26 UTC, helsingborgsstad commented
Task linked: [CU-865ban0hh bugg: pinkod syns ej i ett formulärs sammanfattning](https://app.clickup.com/t/865ban0hh)

2022-12-15 16:07 UTC, MasterKenth requested changes

2022-12-15 16:07 UTC, MasterKenth commented on source/screens/form/FormCaseScreen.tsx
> +  const [loadingEncryptionPin, setLoadinEncryptionpin] = useState(true);
No G in "loading", or capital P in "pin" for `setLoadinEncryptionpin` - literally unusable code I'm afraid.

2022-12-16 08:34 UTC, MasterKenth approved these changes

2022-12-16 08:34 UTC, merged