feat: add ContactCard component instead of administrators display
helsingborg-stad/app-mitt-helsingborg pull request #854
Opened 2023-03-10 13:36 UTC by MasterKenth

## Explain the changes you’ve made

Replaced administrators ("Mina Kontaktpersoner") with a more generic "Contacts" property from the case. Description supports markdown.

## Explain why these changes are made

Administrators are no longer a point of contact for EKB and instead generic contact information needs to be displayed. With this PR the contact information can more generically be specified by the API. (NOTE: API not updated yet - no contacts will be shown).

## Explain your solution

* Added new ContactCard component, based on how administrators were rendered before
* Use `case.contacts` property instead of `case.details.administrators` with slightly different structure

## How to test

Concrete example:

1. Checkout this branch
2. Open a case summary and verify that no contacts are shown (see image)
3. Add to the case and verify that contacts are shown:

```json
{
  ...
  "contacts": [{
      "name": "Kontaktcenter",
      "description":
        "Ring Kontaktcenter [042-10 50 00](tel://042105000). Där kan du få svar på frågor om ditt ärende.",
    }
  ]
}
```

## Tested environments

- [x] Storybook on a iOS device/simulator.
- [x] Building the Application on a iOS device/simulator.
- [x] Building the Application on a Android device/simulator.

## Screenshots

With contact:
<img width="414" alt="image" src="https://user-images.githubusercontent.com/2890987/224328611-953ee2d1-5520-4268-ae30-38f61aa1d9d0.png">

No contacts:
<img width="414" alt="image" src="https://user-images.githubusercontent.com/2890987/224328652-80c1d355-3835-4d02-94f1-f0943da4171b.png">

2023-03-10 14:15 UTC, dannil76 requested changes

2023-03-10 14:15 UTC, dannil76 commented on source/components/molecules/ContactCard/ContactCard.tsx
> +    <Card key={`${name}`} colorSchema="red">
Behöver du göra såhär? Duger inte key={name} bara?

2023-03-13 08:48 UTC, helsingborgsstad commented
Task linked: [CU-865be5re9 Som utvecklare vill jag slå ihop HTML/PDF-genereringen för löpande och grundansökan så att utvecklingen och förvaltningen blir simplare](https://app.clickup.com/t/865be5re9)

2023-03-13 09:01 UTC, helsingborgsstad commented
Task linked: [CU-865bx1jan Hantera nytt data format för kontaktinformation under detaljvyn](https://app.clickup.com/t/865bx1jan)

2023-03-13 09:44 UTC, merged